### ISSUE TITLE
Deprecation

### ISSUE THREAD

**Issue by asowers1** [bitrise-steplib/steps-recursive-touch#1]
Hi there, my team and I are wondering what we should do (if anything) since this step is deprecated. Is it safe to remove it from our workflow or should we replace it with something else? Thanks!

**Comment by bitce** [comment]
Hi @asowers1!

This step was deprecated because the new build system (the Xcode 10.2 final release if I recall correctly) broke this solution completely. 

It is 100% safe to remove from your workflow, there is no harm here, you shouldn't really experience any issues due to this, it's just pointless to keep it since it should have no effect on your builds above this Xcode version.

**Comment by karim-alweheshy** [comment]
@bitce Do you think this is still broken on Xcode 13? It would save the whole community time to fix a solution here

**Comment by bitce** [comment]
hi @KarimAlweheshy, unfortunately, the direction Xcode went in made it impossible to take advantage of this solution completely. We don't see anything indicating that this would've changed, do not expect this specific solution to be working in the future.
